.\" This manpage is Copyright (C) 2010 IBM
.\" Written by Mike Kravetz <kravetz@us.ibm.com>
.\"
.TH LIBCOPMALLOC 3 2010-06-30 "Libcop" "Libcop Programmer's Manual"
.SH NAME
libcopmalloc \- Coprocessor mapped memory management Library
.SH SYNOPSIS
.B #include <libcopmalloc.h>
.SH DESCRIPTION
A pool based memory allocator where memory is already mapped
by the PBIC.


.SH SEE ALSO
.nf
cop_malloc(3)
cop_cache(3)
