.\" This manpage is Copyright (C) 2010 IBM
.\" Written by Mike Kravetz <kravetz@us.ibm.com>
.\"
.TH LIBCOPMANAGE 3 2010-06-30 "Libcop" "Libcop Programmer's Manual"
.SH NAME
libcopmanage \- Basic Coprocessor management Library
.SH SYNOPSIS
.B #include <libcopmanage.h>
.SH DESCRIPTION
Library containing basic interfaces for defling with coprocessors.

.SH SEE ALSO
.nf
cop_manage(3)
