.\" This manpage is Copyright (C) 2010 IBM
.\" Written by Mike Kravetz <kravetz@us.ibm.com>
.\"
.TH LIBCOP 3 2010-06-30 "Libcop" "Libcop Programmer's Manual"
.SH NAME
libcop \- High Level Coprocessor Access Library
.SH SYNOPSIS
.B #include <libcop.h>
.SH DESCRIPTION
An implementation of coprocessor routines for everything from
random number generation, copying memory, symmetric and asymmetric
cryptography, compression / decompress and so on.

.SH SEE ALSO
.nf
cop_asym_crypto(3)
cop_cache(3)
cop_asym_crypto(3)
cop_comp(3)
cop_data_move(3)
cop_data_move_async(3)
cop_malloc(3)
cop_rand(3)
cop_regx(3)
cop_session(3)
cop_sym_crypto(3)
cop_sym_crypto_async(3)
